# **Pandas practice and notes**
---

In [ ]:
#installing pandas library

pip install pandas

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
#importing pandas library and checking the version

import pandas as pd
print(pd.__version__)

2.2.2

# **DataFrames in Pandas**
---
> A pandas DataFrame is a two-dimensional, size-mutable, and labeled data structure in Python, similar to a spreadsheet or SQL table

In [ ]:
#creating dataframe


df = pd.DataFrame([11,22,33])
print(df)

    0
0  11
1  22
2  33

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
#creating dataframe with column header

df = pd.DataFrame([11,22,33],columns=["column_name"])
print(df)

   column_name
0           11
1           22
2           33

In [ ]:
# using Dictionary of Lists
data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita', 'Rishabh'],
    'Age': [16,17,18,19],
    'Salary': [90000, 70000, 50000, 30000]
}

In [ ]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

# **Basic Exploration of DataFrames**
---

In [ ]:
df.head()      #first 5 rows
df.tail()      #last 5 rows
df.info()      #gives overall info
df.describe()  #gives stats about the df
df.shape       #rows and columns count
df.columns     #column names

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

Index(['Name', 'Age', 'Salary'], dtype='object')

In [ ]:
df

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [ ]:
#gives general info about the dataframe

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
#gives top 5 rows by default

df.head(2)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000

In [ ]:
#gives last 5 rows by default

df.tail(2)

      Name  Age  Salary
2   Lalita   18   50000
3  Rishabh   19   30000

In [ ]:
#gives stats about the df

df.describe()

             Age        Salary
count   4.000000      4.000000
mean   17.500000  60000.000000
std     1.290994  25819.888975
min    16.000000  30000.000000
25%    16.750000  45000.000000
50%    17.500000  60000.000000
75%    18.250000  75000.000000
max    19.000000  90000.000000

In [ ]:
#gives (rows,columns) count

df.shape

(4, 3)

In [ ]:
#gives dataframe column names

df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

# **Saving DataFrame to csv file**
---

In [ ]:
#saving dataframe in csv format without index

df.to_csv("test_data.csv",index=False)

# **Selecting & Filtering Data**
---

In [ ]:
#selecting single column

df["Name"]

0      Madhav
1    Vishakha
2      Lalita
3     Rishabh
Name: Name, dtype: object

In [ ]:
#selecting multiple columns

df[["Name", "Salary"]]

       Name  Salary
0    Madhav   90000
1  Vishakha   70000
2    Lalita   50000
3   Rishabh   30000

In [ ]:
#Filtering data

df[df['Age'] > 17]

      Name  Age  Salary
2   Lalita   18   50000
3  Rishabh   19   30000

# **Adding, Modifying and Deleting Columns**
---

In [ ]:
#Adding Column

df["Bonus"] = df["Salary"] * 0.1

In [ ]:
#Adding a column

df["Total_Salary"] = df["Salary"] + df["Bonus"]
df["Team"] = "Team_A"
df

  Employee_Name  Age  Salary   Bonus  Total_Salary    Team
0        Madhav   16   90000  9000.0       99000.0  Team_A
1      Vishakha   17   70000  7000.0       77000.0  Team_A
2        Lalita   18  100000  5000.0      105000.0  Team_A
3       Rishabh   19   30000  3000.0       33000.0  Team_A

In [ ]:
df

  Employee_Name  Age  Salary   Bonus  Total_Salary    Team
0        Madhav   16   90000  9000.0       99000.0  Team_A
1      Vishakha   17   70000  7000.0       77000.0  Team_A
2        Lalita   18  100000  5000.0      105000.0  Team_A
3       Rishabh   19   30000  3000.0       33000.0  Team_A

In [ ]:
#Renaming column

df.rename(columns={"Name":"Employee_Name"},inplace=True)

In [ ]:
#Updating value - using position


df.loc[2,"Salary"] = 100000
df

  Employee_Name  Age  Salary   Bonus  Total_Salary    Team
0        Madhav   16   90000  9000.0       99000.0  Team_A
1      Vishakha   17   70000  7000.0       77000.0  Team_A
2        Lalita   18  100000  5000.0      105000.0  Team_A
3       Rishabh   19   30000  3000.0       33000.0  Team_A

In [ ]:
#deleting a column... axis=1

df.drop("Team",axis=1,inplace=True)
df

  Employee_Name  Age  Salary   Bonus  Total_Salary
0        Madhav   16   90000  9000.0       99000.0
1      Vishakha   17   70000  7000.0       77000.0
2        Lalita   18  100000  5000.0      105000.0
3       Rishabh   19   30000  3000.0       33000.0

In [ ]:
#deleting a row... axis=0

df.drop(3,axis=0,inplace=True)
df

  Employee_Name  Age  Salary   Bonus  Total_Salary
0        Madhav   16   90000  9000.0       99000.0
1      Vishakha   17   70000  7000.0       77000.0
2        Lalita   18  100000  5000.0      105000.0

In [ ]:
df.to_csv("test_data.csv",index=False)

In [ ]:
#reading saved csv file

pd.read_csv("test_data.csv")

  Employee_Name  Age  Salary   Bonus  Total_Salary
0        Madhav   16   90000  9000.0       99000.0
1      Vishakha   17   70000  7000.0       77000.0
2        Lalita   18  100000  5000.0      105000.0

In [ ]:
df

  Employee_Name  Age  Salary   Bonus  Total_Salary
0        Madhav   16   90000  9000.0       99000.0
1      Vishakha   17   70000  7000.0       77000.0
2        Lalita   18  100000  5000.0      105000.0

In [ ]:
#sorting


df.sort_values("Total_Salary",ascending=True,inplace=True)
df

  Employee_Name  Age  Salary   Bonus  Total_Salary
1      Vishakha   17   70000  7000.0       77000.0
0        Madhav   16   90000  9000.0       99000.0
2        Lalita   18  100000  5000.0      105000.0

## **Row Selection**

---
> df.loc → label-based indexing

> df.iloc → position-based indexing

In [ ]:
#Row selection using loc -- label-based indexing

df.loc[(df.Employee_Name=="Lalita")] #by label name

  Employee_Name  Age  Salary   Bonus
2        Lalita   18  100000  5000.0

In [ ]:
#Row selection using iloc -- position-based indexing

df.iloc[2]  # by index

Employee_Name    Lalita
Age                  18
Salary           100000
Bonus            5000.0
Name: 2, dtype: object

In [ ]:
df.iloc[0:2]     # by index

  Employee_Name  Age  Salary   Bonus
0        Madhav   16   90000  9000.0
1      Vishakha   17   70000  7000.0

# **Working date values**
---

In [ ]:
#adding date column

df["DOJ"] = pd.to_datetime("2023-01-01")
df

  Employee_Name  Age  Salary   Bonus  Total_Salary        DOJ
1      Vishakha   17   70000  7000.0       77000.0 2023-01-01
0        Madhav   16   90000  9000.0       99000.0 2023-01-01
2        Lalita   18  100000  5000.0      105000.0 2023-01-01

In [ ]:
df["DOJ"].dtype

dtype('<M8[ns]')

# **Handling Missing Values**
---
> df.isnull() — Identify missing values

> df.dropna() — Dropping null values

> df.fillna() — Replace missing values

In [ ]:
df

  Employee_Name  Age  Salary   Bonus  Total_Salary        DOJ
1      Vishakha   17   70000  7000.0       77000.0 2023-01-01
0        Madhav   16   90000  9000.0       99000.0 2023-01-01
2        Lalita   18  100000  5000.0      105000.0 2023-01-01

In [ ]:
#checking for NULL values

df.isnull()

   Employee_Name    Age  Salary  Bonus  Total_Salary    DOJ
1          False  False   False  False         False  False
0          False  False   False  False         False  False
2          False  False   False  False         False  False

In [ ]:
#creating NULL value for test case

import numpy as np
df.loc[df.Employee_Name=='Madhav','Bonus'] = np.nan

In [ ]:
df

  Employee_Name  Age  Salary   Bonus  Total_Salary        DOJ
1      Vishakha   17   70000  7000.0       77000.0 2023-01-01
0        Madhav   16   90000     NaN       99000.0 2023-01-01
2        Lalita   18  100000  5000.0      105000.0 2023-01-01

In [ ]:
df.isnull()

   Employee_Name    Age  Salary  Bonus  Total_Salary    DOJ
1          False  False   False  False         False  False
0          False  False   False   True         False  False
2          False  False   False  False         False  False

In [ ]:
df.isnull().sum()

Employee_Name    0
Age              0
Salary           0
Bonus            1
Total_Salary     0
DOJ              0
dtype: int64

In [ ]:
#replacing null value

df.fillna(0)

  Employee_Name  Age  Salary   Bonus  Total_Salary        DOJ
1      Vishakha   17   70000  7000.0       77000.0 2023-01-01
0        Madhav   16   90000     0.0       99000.0 2023-01-01
2        Lalita   18  100000  5000.0      105000.0 2023-01-01

# **Aggregation and Group by**
---

In [ ]:
#count -- Frequency analysis

df['Employee_Name'].value_counts()

Employee_Name
Vishakha    1
Madhav      1
Lalita      1
Name: count, dtype: int64

In [ ]:
#Group by column name

df.groupby('DOJ')["Salary"].sum()

DOJ
2023-01-01    260000
Name: Salary, dtype: int64

In [ ]:
df.groupby('DOJ')["Salary"].mean()

DOJ
2023-01-01    86666.666667
Name: Salary, dtype: float64

# **Merge DataFrame | Joins**
---

In [ ]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [ ]:
df2 = pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [ ]:
# Concatenate: vertical/row-level/top on top
pd.concat([df1, df2], axis=0)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [ ]:
# Concatenate: horizontal/column-level/side on side
pd.concat([df1, df2], axis=1)

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [ ]:
#merging DataFrames -- JOINS

pd.merge(df1, df2, on="ID", how="inner")

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77